---
title: "R CODES FOR DASHBOARD"
---

Start fresh

```{r}
library(jsonlite)
library(dplyr)
library(sf)
library(leaflet)
library(tmap)
library(flexdashboard)
library(geojsonio)
```

Paste links from GitHub here:

```{r}
# paste inside the quotations


jsonlink='https://raw.githubusercontent.com/aditipabal/worldindicator-europe/refs/heads/main/worldindicators.json'
```

Have the maps into R

```{r}
world_sf <- geojson_read(jsonlink, what = "sp") %>% st_as_sf()
world_sf <- world_sf %>% rename_with(~ gsub("properties\\.", "", .x))

# Filter Europe
europe_sf <- world_sf %>% filter(region == "EUROPE")
```

See and save plots:

```{r}
tmap_mode("view")
choropleth_map <- tm_shape(europe_sf) +
  tm_polygons("mobiles",
              style = "quantile",
              palette = "Blues",
              title = "Mobile Subscribers") +
  tm_layout(title = "Choropleth Map - Europe")

choropleth_map

```

```{r}
dot_map <- tm_shape(europe_sf) +
  tm_dots("mobiles",
          scale = 0.1,
          col = "blue",
          size = "mobiles",
          title = "Mobile Subscribers") +
  tm_layout(title = "Dot Density Map - Europe")

dot_map

```

```{r}
prop_map <- tm_shape(europe_sf) +
  tm_bubbles(size = "mobiles",
             col = "red",
             alpha = 0.5,
             border.col = "black",
             title.size = "Mobiles") +
  tm_layout(title = "Proportional Symbols Map - Europe")

prop_map
```
